version: "3.8"


services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:latest
    environment:
        - COMPOSE_PROJECT_NAME=qtool
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/certbot/conf:/etc/letsencrypt
      - ../nginx/certbot/data:/var/www/certbot
      - ../nginx/dhparam:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443

  qtool-api:
    restart: always
    container_name: qtool-api
    image: qtum/qtool-api:latest
    build: path=../qtool-api/
    environment:
        - COMPOSE_PROJECT_NAME=qtool
    ports:
      - 8080:8080

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email alejo@qtum.info --agree-tos --no-eff-email --staging -d remix.qtum.info
    volumes:
        - ../nginx/certbot/conf:/etc/letsencrypt
        - ../nginx/certbot/logs:/var/log/letsencrypt
        - ../nginx/certbot/data:/var/www/certbot