version: "3.8"


services:

  qtool-api:
    restart: always
    container_name: qtool-api
    image: qtum/qtool-api:latest
    build:
      context: ../
      dockerfile: Dockerfile

    environment:
        - COMPOSE_PROJECT_NAME=qtool
    ports:
      - 8080:8080

  qtool-react:
    restart: always
    container_name: qtool-react
    image: qtum/qtool-react:dev
    build:
      context: ../react-web-app/
      dockerfile: Dockerfile.dev
    environment:
        - COMPOSE_PROJECT_NAME=qtool
        - NODE_ENV=development
    ports:
      - 3000:3000
